ci: test built node images have correct version
CircleCI-Public/cimg-node pull request #244
Opened 2022-05-11 20:01 UTC by KyleTryon

2022-05-11 20:20 UTC, JalexChen requested changes

2022-05-11 20:20 UTC, JalexChen commented on test-node.sh
> +  if [[ "$line" =~ "latest" ]]; then NODE_VERSION="$latest";
this should be lts, not latest

2022-05-12 20:04 UTC, JalexChen approved these changes

2022-05-16 13:39 UTC, KyleTryon commented
@CircleCI-Public/images Appears this is approved but I would prefer to leave it for y'all to merge when you are ready for it.

2022-05-16 13:43 UTC, KyleTryon commented
Edit: actually it looks as if there are still issues with this PR looking at the job output. I forget where we left off here. Going to revisit whats going on.

2022-05-16 17:03 UTC, JalexChen requested changes
can we take the submodule update out until https://github.com/CircleCI-Public/cimg-shared/pull/65 is merged

2022-05-16 18:19 UTC, KyleTryon commented
Here is an example of the test output: 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/33272306/168657197-13a0dac2-80bd-408a-b472-aad6cf2f145e.png">

I am currently struggling to figure out how to remove the unintended submodule changes.

2022-05-19 18:56 UTC, JalexChen approved these changes

2022-05-19 19:09 UTC, felicianotech approved these changes

2022-05-19 19:21 UTC, merged