Publish v19.3.0. [release]
CircleCI-Public/cimg-node pull request #310
Opened 2022-12-14 18:11 UTC by JalexChen

2022-12-14 19:54 UTC, felicianotech requested changes
This is missing the `current` alias.

2022-12-16 00:10 UTC, Royston-Shufflebotham-i2 commented
Given that you're publishing aliases of '19.3.0', '19.3' and 'current', is there a reason you don't also publish a plain '19' alias?

See also #294.

2022-12-16 01:32 UTC, JalexChen commented
> 

hey @Royston-Shufflebotham-i2 - the `current` tag is equivalent to the `19` alias you are asking about. the `lts` tag is equivalent to the `18` version series per the designations at nodejs.org

2022-12-20 20:30 UTC, felicianotech approved these changes

2022-12-20 20:30 UTC, merged